import java_cup.runtime.*;

terminal Integer INTEIRO;
terminal MAIS, MENOS, PTVIRG;

non terminal inicio;
non terminal Integer expr;

start with inicio;

inicio ::= expr:e PTVIRG {: System.out.println(e); :}
         ;

expr ::= expr:a MAIS INTEIRO:b  {: RESULT = a.intValue() + b.intValue(); :}
       | expr:a MENOS INTEIRO:b {: RESULT = a.intValue() - b.intValue(); :}
       | INTEIRO:a              {: RESULT = a.intValue(); :}
       ;